---
- name: Test oracle-db xe from static
  hosts: all
  vars:
    oracle_version: xe
    transport: local
    transport_local: /tmp
    oracle_images:
      - "linux.x64_11gR2_xe.zip"
    oracle_db_swapfile: /oracle-swapfile-docker-xe
  roles:
    - role: lean_delivery.oracle_db
  become: True

