---
- name: Install oracle db
  hosts: all

  roles:
    - role: lean_delivery.oracle_db
      oracle_version: 11
      patch_version: 11.2.0.1
      transport: local
      transport_local: /tmp
      oracle_images:
        - linux.x64_11gR2_database_1of2.zip
        - linux.x64_11gR2_database_2of2.zip
      oracle_db_swapfile: /oracle-swapfile-11
      oracle_db_swap_count: 2048
